-- Auto-generated skills seed (822 skills)
-- Safe to re-run. Does not require a unique constraint on skills.name.

with payload as (
  select '[
  {"name":".NET","category":"Backend"},
  {"name":".NET MAUI","category":"Mobile"},
  {"name":"Accessibility (a11y)","category":"Frontend"},
  {"name":"Active Directory","category":"IT"},
  {"name":"Advanced Excel","category":"Microsoft"},
  {"name":"Agile","category":"Product"},
  {"name":"Airflow","category":"AI/ML"},
  {"name":"Amazon Web Services (AWS)","category":"Cloud"},
  {"name":"Android Development","category":"Mobile"},
  {"name":"Angular","category":"Frontend"},
  {"name":"Angular accessibility","category":"Frontend"},
  {"name":"Angular architecture","category":"Frontend"},
  {"name":"Angular best practices","category":"Frontend"},
  {"name":"Angular component design","category":"Frontend"},
  {"name":"Angular performance","category":"Frontend"},
  {"name":"Angular state management","category":"Frontend"},
  {"name":"Angular testing","category":"Frontend"},
  {"name":"Ansible","category":"DevOps"},
  {"name":"Ansible administration","category":"DevOps"},
  {"name":"Ansible alerting","category":"DevOps"},
  {"name":"Ansible automation","category":"DevOps"},
  {"name":"Ansible best practices","category":"DevOps"},
  {"name":"Ansible hardening","category":"DevOps"},
  {"name":"Ansible monitoring","category":"DevOps"},
  {"name":"Ansible setup","category":"DevOps"},
  {"name":"Ansible troubleshooting","category":"DevOps"},
  {"name":"Ant Design","category":"Frontend"},
  {"name":"Apache","category":"DevOps"},
  {"name":"Apache Kafka","category":"Platform"},
  {"name":"Apache Pulsar","category":"Platform"},
  {"name":"Apache Spark","category":"AI/ML"},
  {"name":"API Gateway","category":"Architecture"},
  {"name":"API Security","category":"Architecture"},
  {"name":"Apollo GraphQL","category":"Backend"},
  {"name":"Application Security","category":"Security"},
  {"name":"ArgoCD","category":"DevOps"},
  {"name":"ArgoCD administration","category":"DevOps"},
  {"name":"ArgoCD alerting","category":"DevOps"},
  {"name":"ArgoCD automation","category":"DevOps"},
  {"name":"ArgoCD best practices","category":"DevOps"},
  {"name":"ArgoCD hardening","category":"DevOps"},
  {"name":"ArgoCD monitoring","category":"DevOps"},
  {"name":"ArgoCD setup","category":"DevOps"},
  {"name":"ArgoCD troubleshooting","category":"DevOps"},
  {"name":"ASP.NET Core","category":"Backend"},
  {"name":"ASP.NET Core API development","category":"Backend"},
  {"name":"ASP.NET Core best practices","category":"Backend"},
  {"name":"ASP.NET Core deployment","category":"Backend"},
  {"name":"ASP.NET Core performance","category":"Backend"},
  {"name":"ASP.NET Core security","category":"Backend"},
  {"name":"ASP.NET Core testing","category":"Backend"},
  {"name":"Assembly","category":"Programming Language"},
  {"name":"Authentication","category":"Backend"},
  {"name":"Authorization","category":"Backend"},
  {"name":"AWS API Gateway","category":"Cloud"},
  {"name":"AWS Athena","category":"Cloud"},
  {"name":"AWS Aurora","category":"Cloud"},
  {"name":"AWS CDK","category":"Cloud"},
  {"name":"AWS Certified Cloud Practitioner","category":"Certification"},
  {"name":"AWS Certified Developer","category":"Certification"},
  {"name":"AWS Certified Solutions Architect","category":"Certification"},
  {"name":"AWS CloudFormation","category":"Cloud"},
  {"name":"AWS CloudFront","category":"Cloud"},
  {"name":"AWS CloudTrail","category":"Cloud"},
  {"name":"AWS CloudWatch","category":"Cloud"},
  {"name":"AWS Cognito","category":"Cloud"},
  {"name":"AWS DynamoDB","category":"Cloud"},
  {"name":"AWS EC2","category":"Cloud"},
  {"name":"AWS ECS","category":"Cloud"},
  {"name":"AWS EKS","category":"Cloud"},
  {"name":"AWS ElastiCache","category":"Cloud"},
  {"name":"AWS EMR","category":"Cloud"},
  {"name":"AWS EventBridge","category":"Cloud"},
  {"name":"AWS Fargate","category":"Cloud"},
  {"name":"AWS Glue","category":"Cloud"},
  {"name":"AWS IAM","category":"Cloud"},
  {"name":"AWS KMS","category":"Cloud"},
  {"name":"AWS Lambda","category":"Cloud"},
  {"name":"AWS RDS","category":"Cloud"},
  {"name":"AWS Redshift","category":"Cloud"},
  {"name":"AWS Route 53","category":"Cloud"},
  {"name":"AWS S3","category":"Cloud"},
  {"name":"AWS Secrets Manager","category":"Cloud"},
  {"name":"AWS SNS","category":"Cloud"},
  {"name":"AWS SQS","category":"Cloud"},
  {"name":"Azure Active Directory","category":"Microsoft"},
  {"name":"Azure AD (Entra ID)","category":"Cloud"},
  {"name":"Azure AKS","category":"Cloud"},
  {"name":"Azure App Service","category":"Cloud"},
  {"name":"Azure Application Insights","category":"Cloud"},
  {"name":"Azure Blob Storage","category":"Cloud"},
  {"name":"Azure Container Apps","category":"Cloud"},
  {"name":"Azure Cosmos DB","category":"Cloud"},
  {"name":"Azure Data Factory","category":"Microsoft"},
  {"name":"Azure Data Lake Storage","category":"Microsoft"},
  {"name":"Azure Developer Associate","category":"Certification"},
  {"name":"Azure DevOps Pipelines","category":"DevOps"},
  {"name":"Azure Event Grid","category":"Microsoft"},
  {"name":"Azure Functions","category":"Cloud"},
  {"name":"Azure Fundamentals (AZ-900)","category":"Certification"},
  {"name":"Azure Key Vault","category":"Cloud"},
  {"name":"Azure Logic Apps","category":"Microsoft"},
  {"name":"Azure Monitor","category":"Cloud"},
  {"name":"Azure Service Bus","category":"Microsoft"},
  {"name":"Azure Solutions Architect Expert","category":"Certification"},
  {"name":"Azure SQL Database","category":"Cloud"},
  {"name":"Azure Synapse Analytics","category":"Microsoft"},
  {"name":"Azure VMs","category":"Cloud"},
  {"name":"Babel","category":"Frontend"},
  {"name":"Backbone.js","category":"Frontend"},
  {"name":"Backup and Recovery","category":"IT"},
  {"name":"Bash","category":"Programming Language"},
  {"name":"BDD","category":"QA"},
  {"name":"BigQuery","category":"Database"},
  {"name":"BigQuery backup","category":"Database"},
  {"name":"BigQuery high availability","category":"Database"},
  {"name":"BigQuery indexing","category":"Database"},
  {"name":"BigQuery migration","category":"Database"},
  {"name":"BigQuery monitoring","category":"Database"},
  {"name":"BigQuery replication","category":"Database"},
  {"name":"BigQuery tuning","category":"Database"},
  {"name":"Bootstrap","category":"Frontend"},
  {"name":"Business Intelligence","category":"AI/ML"},
  {"name":"C","category":"Programming Language"},
  {"name":"C#","category":"Programming Language"},
  {"name":"C++","category":"Programming Language"},
  {"name":"Caching","category":"Backend"},
  {"name":"Caching Strategies","category":"Architecture"},
  {"name":"Cassandra","category":"Database"},
  {"name":"CentOS","category":"DevOps"},
  {"name":"Chai","category":"QA"},
  {"name":"Chakra UI","category":"Frontend"},
  {"name":"Chaos Engineering","category":"DevOps"},
  {"name":"Chart.js","category":"Frontend"},
  {"name":"Chef","category":"DevOps"},
  {"name":"Chroma","category":"AI/ML"},
  {"name":"Chromatic","category":"Frontend"},
  {"name":"CI/CD","category":"DevOps"},
  {"name":"CircleCI","category":"DevOps"},
  {"name":"Cisco CCNA","category":"Certification"},
  {"name":"Cisco CCNP","category":"Certification"},
  {"name":"Clean Architecture","category":"Architecture"},
  {"name":"ClickHouse","category":"Database"},
  {"name":"Cloudflare","category":"Cloud"},
  {"name":"Cloudflare CDN","category":"Cloud"},
  {"name":"Cloudflare DNS","category":"Cloud"},
  {"name":"Cloudflare Pages","category":"Cloud"},
  {"name":"Cloudflare R2","category":"Cloud"},
  {"name":"Cloudflare WAF","category":"Cloud"},
  {"name":"Cloudflare Workers","category":"Cloud"},
  {"name":"Cloudflare Zero Trust","category":"Cloud"},
  {"name":"CockroachDB","category":"Database"},
  {"name":"Compliance","category":"Security"},
  {"name":"CompTIA A+","category":"Certification"},
  {"name":"CompTIA Network+","category":"Certification"},
  {"name":"CompTIA Security+","category":"Certification"},
  {"name":"Computer Vision","category":"AI/ML"},
  {"name":"Confluence","category":"Product"},
  {"name":"Contract Testing","category":"QA"},
  {"name":"Core Web Vitals","category":"Frontend"},
  {"name":"CouchDB","category":"Database"},
  {"name":"CQRS","category":"Backend"},
  {"name":"Cybersecurity","category":"Security"},
  {"name":"Cypress","category":"QA"},
  {"name":"D3.js","category":"Frontend"},
  {"name":"Dart","category":"Programming Language"},
  {"name":"Data Analysis","category":"AI/ML"},
  {"name":"Data Engineering","category":"AI/ML"},
  {"name":"Data Modeling","category":"Database"},
  {"name":"Data Visualization","category":"AI/ML"},
  {"name":"Data Warehousing","category":"AI/ML"},
  {"name":"Database Design","category":"Database"},
  {"name":"Database Transactions","category":"Architecture"},
  {"name":"Databricks","category":"Database"},
  {"name":"Datadog","category":"DevOps"},
  {"name":"Dataverse","category":"Microsoft"},
  {"name":"dbt","category":"AI/ML"},
  {"name":"DDoS Protection","category":"Security"},
  {"name":"Debian","category":"DevOps"},
  {"name":"Deep Learning","category":"AI/ML"},
  {"name":"Design Patterns","category":"Architecture"},
  {"name":"Design Systems","category":"Design"},
  {"name":"DHCP","category":"IT"},
  {"name":"DigitalOcean","category":"Cloud"},
  {"name":"DigitalOcean App Platform","category":"Platform"},
  {"name":"Disaster Recovery","category":"IT"},
  {"name":"Distributed Systems","category":"Architecture"},
  {"name":"Django","category":"Backend"},
  {"name":"Django API development","category":"Backend"},
  {"name":"Django best practices","category":"Backend"},
  {"name":"Django deployment","category":"Backend"},
  {"name":"Django performance","category":"Backend"},
  {"name":"Django security","category":"Backend"},
  {"name":"Django testing","category":"Backend"},
  {"name":"DNS","category":"IT"},
  {"name":"Docker","category":"DevOps"},
  {"name":"Docker administration","category":"DevOps"},
  {"name":"Docker alerting","category":"DevOps"},
  {"name":"Docker automation","category":"DevOps"},
  {"name":"Docker best practices","category":"DevOps"},
  {"name":"Docker Compose","category":"DevOps"},
  {"name":"Docker hardening","category":"DevOps"},
  {"name":"Docker monitoring","category":"DevOps"},
  {"name":"Docker setup","category":"DevOps"},
  {"name":"Docker Swarm","category":"Platform"},
  {"name":"Docker troubleshooting","category":"DevOps"},
  {"name":"Documentation","category":"Product"},
  {"name":"Domain-Driven Design (DDD)","category":"Architecture"},
  {"name":"Drizzle ORM","category":"Database"},
  {"name":"Dynamics 365","category":"Microsoft"},
  {"name":"Dynamics 365 CRM","category":"Microsoft"},
  {"name":"Dynamics 365 Finance and Operations","category":"Microsoft"},
  {"name":"DynamoDB","category":"Database"},
  {"name":"DynamoDB backup","category":"Database"},
  {"name":"DynamoDB high availability","category":"Database"},
  {"name":"DynamoDB indexing","category":"Database"},
  {"name":"DynamoDB migration","category":"Database"},
  {"name":"DynamoDB monitoring","category":"Database"},
  {"name":"DynamoDB replication","category":"Database"},
  {"name":"DynamoDB tuning","category":"Database"},
  {"name":"ECharts","category":"Frontend"},
  {"name":"Elasticsearch","category":"Database"},
  {"name":"Elixir","category":"Programming Language"},
  {"name":"ELT","category":"AI/ML"},
  {"name":"Embeddings","category":"AI/ML"},
  {"name":"Ember.js","category":"Frontend"},
  {"name":"Emotion","category":"Frontend"},
  {"name":"Encryption","category":"Security"},
  {"name":"End-to-End Testing","category":"QA"},
  {"name":"Entity Framework","category":"Backend"},
  {"name":"ESBuild","category":"Frontend"},
  {"name":"ETL","category":"AI/ML"},
  {"name":"Event Sourcing","category":"Backend"},
  {"name":"Event-Driven Architecture","category":"Backend"},
  {"name":"Excel","category":"Microsoft"},
  {"name":"Exchange Online","category":"Microsoft"},
  {"name":"Expo","category":"Mobile"},
  {"name":"Express.js","category":"Backend"},
  {"name":"FastAPI","category":"Backend"},
  {"name":"FastAPI API development","category":"Backend"},
  {"name":"FastAPI best practices","category":"Backend"},
  {"name":"FastAPI deployment","category":"Backend"},
  {"name":"FastAPI performance","category":"Backend"},
  {"name":"FastAPI security","category":"Backend"},
  {"name":"FastAPI testing","category":"Backend"},
  {"name":"Fastify","category":"Backend"},
  {"name":"Figma","category":"Design"},
  {"name":"Firebase","category":"Database"},
  {"name":"Firestore","category":"Database"},
  {"name":"Firewall Management","category":"Security"},
  {"name":"Flask","category":"Backend"},
  {"name":"Flutter","category":"Mobile"},
  {"name":"FluxCD","category":"DevOps"},
  {"name":"Formik","category":"Frontend"},
  {"name":"Framer Motion","category":"Frontend"},
  {"name":"Gatsby","category":"Frontend"},
  {"name":"GCP BigQuery","category":"Cloud"},
  {"name":"GCP Cloud Build","category":"Cloud"},
  {"name":"GCP Cloud Functions","category":"Cloud"},
  {"name":"GCP Cloud Logging","category":"Cloud"},
  {"name":"GCP Cloud Monitoring","category":"Cloud"},
  {"name":"GCP Cloud Run","category":"Cloud"},
  {"name":"GCP Cloud SQL","category":"Cloud"},
  {"name":"GCP Cloud Storage","category":"Cloud"},
  {"name":"GCP Compute Engine","category":"Cloud"},
  {"name":"GCP Firestore","category":"Cloud"},
  {"name":"GCP GKE","category":"Cloud"},
  {"name":"GCP IAM","category":"Cloud"},
  {"name":"GCP Pub/Sub","category":"Cloud"},
  {"name":"GCP Secret Manager","category":"Cloud"},
  {"name":"GitHub Actions","category":"DevOps"},
  {"name":"GitHub Actions administration","category":"DevOps"},
  {"name":"GitHub Actions alerting","category":"DevOps"},
  {"name":"GitHub Actions automation","category":"DevOps"},
  {"name":"GitHub Actions best practices","category":"DevOps"},
  {"name":"GitHub Actions hardening","category":"DevOps"},
  {"name":"GitHub Actions monitoring","category":"DevOps"},
  {"name":"GitHub Actions setup","category":"DevOps"},
  {"name":"GitHub Actions troubleshooting","category":"DevOps"},
  {"name":"GitLab CI/CD","category":"DevOps"},
  {"name":"GitLab CI/CD administration","category":"DevOps"},
  {"name":"GitLab CI/CD alerting","category":"DevOps"},
  {"name":"GitLab CI/CD automation","category":"DevOps"},
  {"name":"GitLab CI/CD best practices","category":"DevOps"},
  {"name":"GitLab CI/CD hardening","category":"DevOps"},
  {"name":"GitLab CI/CD monitoring","category":"DevOps"},
  {"name":"GitLab CI/CD setup","category":"DevOps"},
  {"name":"GitLab CI/CD troubleshooting","category":"DevOps"},
  {"name":"Go","category":"Programming Language"},
  {"name":"Google Associate Cloud Engineer","category":"Certification"},
  {"name":"Google Cloud Platform (GCP)","category":"Cloud"},
  {"name":"Grafana","category":"DevOps"},
  {"name":"Grafana administration","category":"DevOps"},
  {"name":"Grafana alerting","category":"DevOps"},
  {"name":"Grafana automation","category":"DevOps"},
  {"name":"Grafana best practices","category":"DevOps"},
  {"name":"Grafana hardening","category":"DevOps"},
  {"name":"Grafana monitoring","category":"DevOps"},
  {"name":"Grafana setup","category":"DevOps"},
  {"name":"Grafana troubleshooting","category":"DevOps"},
  {"name":"GraphQL","category":"Backend"},
  {"name":"GraphQL API development","category":"Backend"},
  {"name":"GraphQL best practices","category":"Backend"},
  {"name":"GraphQL deployment","category":"Backend"},
  {"name":"GraphQL performance","category":"Backend"},
  {"name":"GraphQL security","category":"Backend"},
  {"name":"GraphQL testing","category":"Backend"},
  {"name":"GraphQL Yoga","category":"Backend"},
  {"name":"Groovy","category":"Programming Language"},
  {"name":"Group Policy","category":"IT"},
  {"name":"gRPC","category":"Backend"},
  {"name":"gRPC API development","category":"Backend"},
  {"name":"gRPC best practices","category":"Backend"},
  {"name":"gRPC deployment","category":"Backend"},
  {"name":"gRPC performance","category":"Backend"},
  {"name":"gRPC security","category":"Backend"},
  {"name":"gRPC testing","category":"Backend"},
  {"name":"GSAP","category":"Frontend"},
  {"name":"Hadoop","category":"AI/ML"},
  {"name":"Hapi","category":"Backend"},
  {"name":"HAProxy","category":"DevOps"},
  {"name":"Hardware Support","category":"IT"},
  {"name":"Haskell","category":"Programming Language"},
  {"name":"Hasura","category":"Backend"},
  {"name":"Helm","category":"DevOps"},
  {"name":"Helpdesk","category":"IT"},
  {"name":"Heroku","category":"Cloud"},
  {"name":"High Availability","category":"Architecture"},
  {"name":"Highcharts","category":"Frontend"},
  {"name":"Hyper-V","category":"IT"},
  {"name":"IAM (Identity and Access Management)","category":"Security"},
  {"name":"IAM best practices","category":"Security"},
  {"name":"IAM configuration","category":"Security"},
  {"name":"IAM implementation","category":"Security"},
  {"name":"IAM troubleshooting","category":"Security"},
  {"name":"Incident Response","category":"Security"},
  {"name":"Incident Response best practices","category":"Security"},
  {"name":"Incident Response configuration","category":"Security"},
  {"name":"Incident Response implementation","category":"Security"},
  {"name":"Incident Response troubleshooting","category":"Security"},
  {"name":"Indexing","category":"Database"},
  {"name":"InfluxDB","category":"Database"},
  {"name":"Information Architecture","category":"Design"},
  {"name":"Integration Testing","category":"QA"},
  {"name":"Intune","category":"Microsoft"},
  {"name":"iOS Development","category":"Mobile"},
  {"name":"IT Support","category":"IT"},
  {"name":"ITIL Foundation","category":"Certification"},
  {"name":"Jaeger","category":"DevOps"},
  {"name":"Java","category":"Programming Language"},
  {"name":"JavaScript","category":"Programming Language"},
  {"name":"Jenkins","category":"DevOps"},
  {"name":"Jenkins administration","category":"DevOps"},
  {"name":"Jenkins alerting","category":"DevOps"},
  {"name":"Jenkins automation","category":"DevOps"},
  {"name":"Jenkins best practices","category":"DevOps"},
  {"name":"Jenkins hardening","category":"DevOps"},
  {"name":"Jenkins monitoring","category":"DevOps"},
  {"name":"Jenkins setup","category":"DevOps"},
  {"name":"Jenkins troubleshooting","category":"DevOps"},
  {"name":"Jest","category":"QA"},
  {"name":"Jetpack Compose","category":"Mobile"},
  {"name":"Jira","category":"Product"},
  {"name":"jQuery","category":"Frontend"},
  {"name":"Julia","category":"Programming Language"},
  {"name":"JWT","category":"Security"},
  {"name":"Kafka Streams","category":"AI/ML"},
  {"name":"Kanban","category":"Product"},
  {"name":"Key Management","category":"Security"},
  {"name":"Koa.js","category":"Backend"},
  {"name":"Kotlin","category":"Programming Language"},
  {"name":"Kotlin Multiplatform","category":"Mobile"},
  {"name":"Kubernetes","category":"DevOps"},
  {"name":"Kubernetes administration","category":"DevOps"},
  {"name":"Kubernetes alerting","category":"DevOps"},
  {"name":"Kubernetes automation","category":"DevOps"},
  {"name":"Kubernetes best practices","category":"DevOps"},
  {"name":"Kubernetes hardening","category":"DevOps"},
  {"name":"Kubernetes monitoring","category":"DevOps"},
  {"name":"Kubernetes setup","category":"DevOps"},
  {"name":"Kubernetes troubleshooting","category":"DevOps"},
  {"name":"Kustomize","category":"DevOps"},
  {"name":"LangChain","category":"AI/ML"},
  {"name":"Laravel","category":"Backend"},
  {"name":"Less","category":"Frontend"},
  {"name":"Linux","category":"DevOps"},
  {"name":"Linux Administration","category":"IT"},
  {"name":"Linux administration","category":"DevOps"},
  {"name":"Linux alerting","category":"DevOps"},
  {"name":"Linux automation","category":"DevOps"},
  {"name":"Linux best practices","category":"DevOps"},
  {"name":"Linux hardening","category":"DevOps"},
  {"name":"Linux monitoring","category":"DevOps"},
  {"name":"Linux setup","category":"DevOps"},
  {"name":"Linux troubleshooting","category":"DevOps"},
  {"name":"Lit","category":"Frontend"},
  {"name":"LlamaIndex","category":"AI/ML"},
  {"name":"LLM Engineering","category":"AI/ML"},
  {"name":"Load Testing","category":"DevOps"},
  {"name":"Logging","category":"DevOps"},
  {"name":"Loki","category":"DevOps"},
  {"name":"Lua","category":"Programming Language"},
  {"name":"M365 Compliance","category":"Microsoft"},
  {"name":"M365 Identity Management","category":"Microsoft"},
  {"name":"M365 Security","category":"Microsoft"},
  {"name":"Machine Learning","category":"AI/ML"},
  {"name":"Mailgun","category":"Platform"},
  {"name":"MariaDB","category":"Database"},
  {"name":"Material UI","category":"Frontend"},
  {"name":"MATLAB","category":"Programming Language"},
  {"name":"Message Queues","category":"Architecture"},
  {"name":"Micronaut","category":"Backend"},
  {"name":"Microservices","category":"Backend"},
  {"name":"Microsoft 365","category":"Microsoft"},
  {"name":"Microsoft Azure","category":"Cloud"},
  {"name":"Microsoft Defender","category":"Microsoft"},
  {"name":"Microsoft Entra ID","category":"Microsoft"},
  {"name":"Microsoft Fabric","category":"Microsoft"},
  {"name":"Microsoft Project","category":"Microsoft"},
  {"name":"Microsoft Sentinel","category":"Microsoft"},
  {"name":"Microsoft SQL Server","category":"Database"},
  {"name":"Microsoft Teams","category":"Microsoft"},
  {"name":"Microsoft Visio","category":"Microsoft"},
  {"name":"Milvus","category":"AI/ML"},
  {"name":"MobX","category":"Frontend"},
  {"name":"Mocha","category":"QA"},
  {"name":"Module Federation","category":"Frontend"},
  {"name":"MongoDB","category":"Database"},
  {"name":"MongoDB backup","category":"Database"},
  {"name":"MongoDB high availability","category":"Database"},
  {"name":"MongoDB indexing","category":"Database"},
  {"name":"MongoDB migration","category":"Database"},
  {"name":"MongoDB monitoring","category":"Database"},
  {"name":"MongoDB replication","category":"Database"},
  {"name":"MongoDB tuning","category":"Database"},
  {"name":"Mongoose","category":"Database"},
  {"name":"Monitoring","category":"DevOps"},
  {"name":"Monolith Architecture","category":"Backend"},
  {"name":"MySQL","category":"Database"},
  {"name":"MySQL backup","category":"Database"},
  {"name":"MySQL high availability","category":"Database"},
  {"name":"MySQL indexing","category":"Database"},
  {"name":"MySQL migration","category":"Database"},
  {"name":"MySQL monitoring","category":"Database"},
  {"name":"MySQL replication","category":"Database"},
  {"name":"MySQL tuning","category":"Database"},
  {"name":"Natural Language Processing","category":"AI/ML"},
  {"name":"Neo4j","category":"Database"},
  {"name":"NestJS","category":"Backend"},
  {"name":"NestJS API development","category":"Backend"},
  {"name":"NestJS best practices","category":"Backend"},
  {"name":"NestJS deployment","category":"Backend"},
  {"name":"NestJS performance","category":"Backend"},
  {"name":"NestJS security","category":"Backend"},
  {"name":"NestJS testing","category":"Backend"},
  {"name":"Netlify","category":"Cloud"},
  {"name":"Network Monitoring","category":"IT"},
  {"name":"Network Security","category":"Security"},
  {"name":"Networking","category":"IT"},
  {"name":"New Relic","category":"DevOps"},
  {"name":"Newman","category":"QA"},
  {"name":"Next.js","category":"Frontend"},
  {"name":"Next.js accessibility","category":"Frontend"},
  {"name":"Next.js architecture","category":"Frontend"},
  {"name":"Next.js best practices","category":"Frontend"},
  {"name":"Next.js component design","category":"Frontend"},
  {"name":"Next.js performance","category":"Frontend"},
  {"name":"Next.js state management","category":"Frontend"},
  {"name":"Next.js testing","category":"Frontend"},
  {"name":"Nginx","category":"DevOps"},
  {"name":"NGINX Ingress","category":"Platform"},
  {"name":"Node.js","category":"Backend"},
  {"name":"Node.js API development","category":"Backend"},
  {"name":"Node.js best practices","category":"Backend"},
  {"name":"Node.js deployment","category":"Backend"},
  {"name":"Node.js performance","category":"Backend"},
  {"name":"Node.js security","category":"Backend"},
  {"name":"Node.js testing","category":"Backend"},
  {"name":"Notion","category":"Product"},
  {"name":"NumPy","category":"AI/ML"},
  {"name":"Nuxt","category":"Frontend"},
  {"name":"OAuth 2.0","category":"Security"},
  {"name":"OAuth best practices","category":"Security"},
  {"name":"OAuth configuration","category":"Security"},
  {"name":"OAuth implementation","category":"Security"},
  {"name":"OAuth troubleshooting","category":"Security"},
  {"name":"Objective-C","category":"Programming Language"},
  {"name":"Observability","category":"DevOps"},
  {"name":"Office 365 Administration","category":"Microsoft"},
  {"name":"OneDrive for Business","category":"Microsoft"},
  {"name":"OpenAI API","category":"AI/ML"},
  {"name":"OpenAPI / Swagger","category":"Backend"},
  {"name":"OpenID Connect","category":"Security"},
  {"name":"OpenID Connect best practices","category":"Security"},
  {"name":"OpenID Connect configuration","category":"Security"},
  {"name":"OpenID Connect implementation","category":"Security"},
  {"name":"OpenID Connect troubleshooting","category":"Security"},
  {"name":"OpenSearch","category":"Database"},
  {"name":"OpenTelemetry","category":"DevOps"},
  {"name":"Oracle backup","category":"Database"},
  {"name":"Oracle Database","category":"Database"},
  {"name":"Oracle high availability","category":"Database"},
  {"name":"Oracle indexing","category":"Database"},
  {"name":"Oracle migration","category":"Database"},
  {"name":"Oracle monitoring","category":"Database"},
  {"name":"Oracle replication","category":"Database"},
  {"name":"Oracle tuning","category":"Database"},
  {"name":"OWASP","category":"Security"},
  {"name":"OWASP Top 10","category":"Security"},
  {"name":"Pact","category":"QA"},
  {"name":"Pandas","category":"AI/ML"},
  {"name":"Parcel","category":"Frontend"},
  {"name":"Paystack","category":"Platform"},
  {"name":"Penetration Testing","category":"Security"},
  {"name":"Performance Engineering","category":"Architecture"},
  {"name":"Performance Optimization","category":"Frontend"},
  {"name":"Performance Testing","category":"DevOps"},
  {"name":"Perl","category":"Programming Language"},
  {"name":"PHP","category":"Programming Language"},
  {"name":"Pinecone","category":"AI/ML"},
  {"name":"PivotTables","category":"Microsoft"},
  {"name":"PKI","category":"Security"},
  {"name":"PKI best practices","category":"Security"},
  {"name":"PKI configuration","category":"Security"},
  {"name":"PKI implementation","category":"Security"},
  {"name":"PKI troubleshooting","category":"Security"},
  {"name":"PL/pgSQL","category":"Programming Language"},
  {"name":"Planner","category":"Microsoft"},
  {"name":"Playwright","category":"QA"},
  {"name":"PostCSS","category":"Frontend"},
  {"name":"PostgreSQL","category":"Database"},
  {"name":"PostgreSQL backup","category":"Database"},
  {"name":"PostgreSQL high availability","category":"Database"},
  {"name":"PostgreSQL indexing","category":"Database"},
  {"name":"PostgreSQL migration","category":"Database"},
  {"name":"PostgreSQL monitoring","category":"Database"},
  {"name":"PostgreSQL replication","category":"Database"},
  {"name":"PostgreSQL RLS","category":"Platform"},
  {"name":"PostgreSQL tuning","category":"Database"},
  {"name":"PostgREST","category":"Backend"},
  {"name":"Postman","category":"QA"},
  {"name":"Power Apps","category":"Microsoft"},
  {"name":"Power Automate","category":"Microsoft"},
  {"name":"Power BI","category":"Microsoft"},
  {"name":"Power BI Data Modeling","category":"Microsoft"},
  {"name":"Power BI DAX","category":"Microsoft"},
  {"name":"Power Pivot","category":"Microsoft"},
  {"name":"Power Platform","category":"Microsoft"},
  {"name":"Power Query","category":"Microsoft"},
  {"name":"PowerShell","category":"Programming Language"},
  {"name":"Prisma","category":"Database"},
  {"name":"Product Management","category":"Product"},
  {"name":"Project Management","category":"Product"},
  {"name":"Prometheus","category":"DevOps"},
  {"name":"Prometheus administration","category":"DevOps"},
  {"name":"Prometheus alerting","category":"DevOps"},
  {"name":"Prometheus automation","category":"DevOps"},
  {"name":"Prometheus best practices","category":"DevOps"},
  {"name":"Prometheus hardening","category":"DevOps"},
  {"name":"Prometheus monitoring","category":"DevOps"},
  {"name":"Prometheus setup","category":"DevOps"},
  {"name":"Prometheus troubleshooting","category":"DevOps"},
  {"name":"Prometheus TSDB","category":"Database"},
  {"name":"Prompt Engineering","category":"AI/ML"},
  {"name":"Prototyping","category":"Design"},
  {"name":"Pulumi","category":"DevOps"},
  {"name":"Puppet","category":"DevOps"},
  {"name":"PWA (Progressive Web Apps)","category":"Frontend"},
  {"name":"Python","category":"Programming Language"},
  {"name":"PyTorch","category":"AI/ML"},
  {"name":"Quarkus","category":"Backend"},
  {"name":"Query Optimization","category":"Database"},
  {"name":"Qwik","category":"Frontend"},
  {"name":"R","category":"Programming Language"},
  {"name":"RabbitMQ","category":"Platform"},
  {"name":"Radix UI","category":"Frontend"},
  {"name":"RAG (Retrieval-Augmented Generation)","category":"AI/ML"},
  {"name":"Railway","category":"Cloud"},
  {"name":"Rate Limiting","category":"Backend"},
  {"name":"React","category":"Frontend"},
  {"name":"React accessibility","category":"Frontend"},
  {"name":"React architecture","category":"Frontend"},
  {"name":"React best practices","category":"Frontend"},
  {"name":"React component design","category":"Frontend"},
  {"name":"React Hook Form","category":"Frontend"},
  {"name":"React Native","category":"Mobile"},
  {"name":"React performance","category":"Frontend"},
  {"name":"React Query","category":"Frontend"},
  {"name":"React state management","category":"Frontend"},
  {"name":"React testing","category":"Frontend"},
  {"name":"Recoil","category":"Frontend"},
  {"name":"Red Hat","category":"DevOps"},
  {"name":"Redis","category":"Database"},
  {"name":"Redis backup","category":"Database"},
  {"name":"Redis high availability","category":"Database"},
  {"name":"Redis indexing","category":"Database"},
  {"name":"Redis migration","category":"Database"},
  {"name":"Redis monitoring","category":"Database"},
  {"name":"Redis Pub/Sub","category":"Platform"},
  {"name":"Redis replication","category":"Database"},
  {"name":"Redis tuning","category":"Database"},
  {"name":"Redshift","category":"Database"},
  {"name":"Redux","category":"Frontend"},
  {"name":"Redux Toolkit","category":"Frontend"},
  {"name":"Reliability Engineering","category":"Architecture"},
  {"name":"Remix","category":"Frontend"},
  {"name":"Render","category":"Cloud"},
  {"name":"Replication","category":"Database"},
  {"name":"Resend","category":"Platform"},
  {"name":"REST API Development","category":"Backend"},
  {"name":"Risk Management","category":"Security"},
  {"name":"Roadmapping","category":"Product"},
  {"name":"Rollup","category":"Frontend"},
  {"name":"Routing","category":"IT"},
  {"name":"Row Level Security (RLS)","category":"Platform"},
  {"name":"RTK Query","category":"Frontend"},
  {"name":"Ruby","category":"Programming Language"},
  {"name":"Ruby on Rails","category":"Backend"},
  {"name":"Rust","category":"Programming Language"},
  {"name":"SAML","category":"Security"},
  {"name":"SAML best practices","category":"Security"},
  {"name":"SAML configuration","category":"Security"},
  {"name":"SAML implementation","category":"Security"},
  {"name":"SAML troubleshooting","category":"Security"},
  {"name":"Sass","category":"Frontend"},
  {"name":"Scala","category":"Programming Language"},
  {"name":"Scalability","category":"Architecture"},
  {"name":"Scikit-learn","category":"AI/ML"},
  {"name":"Scrum","category":"Product"},
  {"name":"Secure Coding","category":"Security"},
  {"name":"Security Auditing","category":"Security"},
  {"name":"Selenium","category":"QA"},
  {"name":"SendGrid","category":"Platform"},
  {"name":"Sentry","category":"DevOps"},
  {"name":"Sequelize","category":"Database"},
  {"name":"Serverless Architecture","category":"Backend"},
  {"name":"Service Desk","category":"IT"},
  {"name":"Service Workers","category":"Frontend"},
  {"name":"Shadcn UI","category":"Frontend"},
  {"name":"Sharding","category":"Database"},
  {"name":"SharePoint","category":"Microsoft"},
  {"name":"SharePoint Administration","category":"Microsoft"},
  {"name":"SharePoint Framework (SPFx)","category":"Microsoft"},
  {"name":"SharePoint Online","category":"Microsoft"},
  {"name":"Shell Scripting","category":"Programming Language"},
  {"name":"SIEM","category":"Security"},
  {"name":"SIEM best practices","category":"Security"},
  {"name":"SIEM configuration","category":"Security"},
  {"name":"SIEM implementation","category":"Security"},
  {"name":"SIEM troubleshooting","category":"Security"},
  {"name":"Sinatra","category":"Backend"},
  {"name":"SLA/SLO/SLI","category":"Architecture"},
  {"name":"Snowflake","category":"Database"},
  {"name":"Snowflake backup","category":"Database"},
  {"name":"Snowflake high availability","category":"Database"},
  {"name":"Snowflake indexing","category":"Database"},
  {"name":"Snowflake migration","category":"Database"},
  {"name":"Snowflake monitoring","category":"Database"},
  {"name":"Snowflake replication","category":"Database"},
  {"name":"Snowflake tuning","category":"Database"},
  {"name":"SOAR","category":"Security"},
  {"name":"SOC Operations","category":"Security"},
  {"name":"Socket.IO","category":"Platform"},
  {"name":"Software Architecture","category":"Architecture"},
  {"name":"Software Support","category":"IT"},
  {"name":"Solidity","category":"Programming Language"},
  {"name":"SolidJS","category":"Frontend"},
  {"name":"Splunk","category":"DevOps"},
  {"name":"Spring Boot","category":"Backend"},
  {"name":"Spring Boot API development","category":"Backend"},
  {"name":"Spring Boot best practices","category":"Backend"},
  {"name":"Spring Boot deployment","category":"Backend"},
  {"name":"Spring Boot performance","category":"Backend"},
  {"name":"Spring Boot security","category":"Backend"},
  {"name":"Spring Boot testing","category":"Backend"},
  {"name":"SQL","category":"Programming Language"},
  {"name":"SQL Server backup","category":"Database"},
  {"name":"SQL Server high availability","category":"Database"},
  {"name":"SQL Server indexing","category":"Database"},
  {"name":"SQL Server migration","category":"Database"},
  {"name":"SQL Server monitoring","category":"Database"},
  {"name":"SQL Server replication","category":"Database"},
  {"name":"SQL Server tuning","category":"Database"},
  {"name":"SQLAlchemy","category":"Database"},
  {"name":"SQLite","category":"Database"},
  {"name":"SSO","category":"Security"},
  {"name":"Stakeholder Management","category":"Product"},
  {"name":"Stencil","category":"Frontend"},
  {"name":"Storybook","category":"Frontend"},
  {"name":"Storybook accessibility","category":"Frontend"},
  {"name":"Storybook architecture","category":"Frontend"},
  {"name":"Storybook best practices","category":"Frontend"},
  {"name":"Storybook component design","category":"Frontend"},
  {"name":"Storybook performance","category":"Frontend"},
  {"name":"Storybook state management","category":"Frontend"},
  {"name":"Storybook testing","category":"Frontend"},
  {"name":"Stripe","category":"Platform"},
  {"name":"Styled Components","category":"Frontend"},
  {"name":"Supabase","category":"Database"},
  {"name":"Supabase Auth","category":"Platform"},
  {"name":"Svelte","category":"Frontend"},
  {"name":"SvelteKit","category":"Frontend"},
  {"name":"Swift","category":"Programming Language"},
  {"name":"SwiftUI","category":"Mobile"},
  {"name":"Switching","category":"IT"},
  {"name":"SWR","category":"Frontend"},
  {"name":"Symfony","category":"Backend"},
  {"name":"System Design","category":"Architecture"},
  {"name":"T-SQL","category":"Programming Language"},
  {"name":"Tailwind CSS","category":"Frontend"},
  {"name":"Tailwind CSS accessibility","category":"Frontend"},
  {"name":"Tailwind CSS architecture","category":"Frontend"},
  {"name":"Tailwind CSS best practices","category":"Frontend"},
  {"name":"Tailwind CSS component design","category":"Frontend"},
  {"name":"Tailwind CSS performance","category":"Frontend"},
  {"name":"Tailwind CSS state management","category":"Frontend"},
  {"name":"Tailwind CSS testing","category":"Frontend"},
  {"name":"TanStack Query","category":"Frontend"},
  {"name":"TCP/IP","category":"IT"},
  {"name":"TDD","category":"QA"},
  {"name":"Technical Writing","category":"Product"},
  {"name":"Tempo","category":"DevOps"},
  {"name":"TensorFlow","category":"AI/ML"},
  {"name":"Terraform","category":"DevOps"},
  {"name":"Terraform administration","category":"DevOps"},
  {"name":"Terraform alerting","category":"DevOps"},
  {"name":"Terraform automation","category":"DevOps"},
  {"name":"Terraform best practices","category":"DevOps"},
  {"name":"Terraform hardening","category":"DevOps"},
  {"name":"Terraform monitoring","category":"DevOps"},
  {"name":"Terraform setup","category":"DevOps"},
  {"name":"Terraform troubleshooting","category":"DevOps"},
  {"name":"Test Automation","category":"QA"},
  {"name":"Threat Modeling","category":"Security"},
  {"name":"Three.js","category":"Frontend"},
  {"name":"TimescaleDB","category":"Database"},
  {"name":"TLS best practices","category":"Security"},
  {"name":"TLS configuration","category":"Security"},
  {"name":"TLS implementation","category":"Security"},
  {"name":"TLS troubleshooting","category":"Security"},
  {"name":"TLS/SSL","category":"Security"},
  {"name":"Traefik","category":"Platform"},
  {"name":"Travis CI","category":"DevOps"},
  {"name":"Troubleshooting","category":"IT"},
  {"name":"tRPC","category":"Backend"},
  {"name":"Twilio","category":"Platform"},
  {"name":"TypeORM","category":"Database"},
  {"name":"TypeScript","category":"Programming Language"},
  {"name":"TypeScript accessibility","category":"Frontend"},
  {"name":"TypeScript architecture","category":"Frontend"},
  {"name":"TypeScript best practices","category":"Frontend"},
  {"name":"TypeScript component design","category":"Frontend"},
  {"name":"TypeScript performance","category":"Frontend"},
  {"name":"TypeScript state management","category":"Frontend"},
  {"name":"TypeScript testing","category":"Frontend"},
  {"name":"Ubuntu","category":"DevOps"},
  {"name":"UI Design","category":"Design"},
  {"name":"Unit Testing","category":"QA"},
  {"name":"Usability Testing","category":"Design"},
  {"name":"User Research","category":"Design"},
  {"name":"UX Design","category":"Design"},
  {"name":"VB.NET","category":"Programming Language"},
  {"name":"VBA","category":"Microsoft"},
  {"name":"Vector Databases","category":"AI/ML"},
  {"name":"Vercel","category":"Cloud"},
  {"name":"Virtualization","category":"IT"},
  {"name":"Vite","category":"Frontend"},
  {"name":"Vite accessibility","category":"Frontend"},
  {"name":"Vite architecture","category":"Frontend"},
  {"name":"Vite best practices","category":"Frontend"},
  {"name":"Vite component design","category":"Frontend"},
  {"name":"Vite performance","category":"Frontend"},
  {"name":"Vite state management","category":"Frontend"},
  {"name":"Vite testing","category":"Frontend"},
  {"name":"Vitest","category":"QA"},
  {"name":"VLANs","category":"IT"},
  {"name":"VMware","category":"IT"},
  {"name":"VPN","category":"IT"},
  {"name":"Vue.js","category":"Frontend"},
  {"name":"Vue.js accessibility","category":"Frontend"},
  {"name":"Vue.js architecture","category":"Frontend"},
  {"name":"Vue.js best practices","category":"Frontend"},
  {"name":"Vue.js component design","category":"Frontend"},
  {"name":"Vue.js performance","category":"Frontend"},
  {"name":"Vue.js state management","category":"Frontend"},
  {"name":"Vue.js testing","category":"Frontend"},
  {"name":"Vulnerability Management","category":"Security"},
  {"name":"WAF","category":"Security"},
  {"name":"WAF best practices","category":"Security"},
  {"name":"WAF configuration","category":"Security"},
  {"name":"WAF implementation","category":"Security"},
  {"name":"WAF troubleshooting","category":"Security"},
  {"name":"Weaviate","category":"AI/ML"},
  {"name":"Web Components","category":"Frontend"},
  {"name":"WebGL","category":"Frontend"},
  {"name":"Webpack","category":"Frontend"},
  {"name":"Webpack accessibility","category":"Frontend"},
  {"name":"Webpack architecture","category":"Frontend"},
  {"name":"Webpack best practices","category":"Frontend"},
  {"name":"Webpack component design","category":"Frontend"},
  {"name":"Webpack performance","category":"Frontend"},
  {"name":"Webpack state management","category":"Frontend"},
  {"name":"Webpack testing","category":"Frontend"},
  {"name":"WebRTC","category":"Platform"},
  {"name":"WebSockets","category":"Backend"},
  {"name":"Wi-Fi","category":"IT"},
  {"name":"Windows","category":"IT"},
  {"name":"Windows 10","category":"Microsoft"},
  {"name":"Windows 11","category":"Microsoft"},
  {"name":"Windows Server","category":"IT"},
  {"name":"Wireframing","category":"Design"},
  {"name":"Xamarin","category":"Mobile"},
  {"name":"XGBoost","category":"AI/ML"},
  {"name":"XState","category":"Frontend"},
  {"name":"Yup","category":"Frontend"},
  {"name":"Zero Trust","category":"Security"},
  {"name":"Zero Trust best practices","category":"Security"},
  {"name":"Zero Trust configuration","category":"Security"},
  {"name":"Zero Trust implementation","category":"Security"},
  {"name":"Zero Trust troubleshooting","category":"Security"},
  {"name":"Zod","category":"Frontend"},
  {"name":"Zustand","category":"Frontend"}
]'::jsonb as data
),
rows as (
  select
    left(r.name, 150)::varchar(150) as name,
    nullif(left(r.category, 100), '')::varchar(100) as category
  from payload,
  jsonb_to_recordset(payload.data) as r(name text, category text)
),
updated as (
  update public.skills s
  set category = rows.category
  from rows
  where lower(s.name) = lower(rows.name)
  returning lower(s.name) as norm_name
)
insert into public.skills (name, category)
select rows.name, rows.category
from rows
where not exists (
  select 1 from updated u where u.norm_name = lower(rows.name)
)
and not exists (
  select 1 from public.skills s where lower(s.name) = lower(rows.name)
);
